# Generated by Django 4.2.4 on 2023-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0002_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(to='magazon_app.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подкатегория'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
