# Generated by Django 4.2.4 on 2023-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0005_bodytype_carbrand_carcolor_carestate_carmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Легковой автомобиль', 'verbose_name_plural': 'Легковые автомобили'},
        ),
        migrations.RemoveField(
            model_name='cars',
            name='region',
        ),
    ]
