# Generated by Django 4.2.4 on 2023-09-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0007_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='magazon_app.region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='magazon_app.category'),
        ),
    ]
