# Generated by Django 4.2.4 on 2023-09-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0008_alter_city_region_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='magazon_app.region', verbose_name='Область'),
        ),
    ]
