# Generated by Django 4.2.4 on 2023-09-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0010_carmodel_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
    ]
