# Generated by Django 4.2.4 on 2023-09-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0013_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
