# Generated by Django 4.2.4 on 2023-09-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0014_remove_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
