# Generated by Django 4.2.4 on 2023-09-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0018_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
