# Generated by Django 4.2.4 on 2023-09-06 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazon_app', '0021_alter_driveunit_options_remove_cars_likes_cars_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марку',
                'verbose_name_plural': 'Марки грузовых авто',
            },
        ),
        migrations.CreateModel(
            name='TruckLoadCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Грузоподъемность')),
            ],
            options={
                'verbose_name': 'Грузоподъемность',
                'verbose_name_plural': 'Грузоподъемности грузовых авто',
            },
        ),
        migrations.CreateModel(
            name='TruckTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'Коробку передач',
                'verbose_name_plural': 'Типы коробки передач грузовых авто',
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип грузовика')),
            ],
            options={
                'verbose_name': 'Тип грузовика',
                'verbose_name_plural': 'Типы грузовиков',
            },
        ),
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название товара/услуги')),
                ('mileage', models.IntegerField(verbose_name='Пробег, км')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('exchange', models.BooleanField(verbose_name='Возможен обмен')),
                ('leasing', models.BooleanField(verbose_name='Лизинг от продавца')),
                ('installment_plan', models.BooleanField(verbose_name='Готов(а) продать товар в рассрочку')),
                ('grade', models.FloatField(default=0, verbose_name='Оценка')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.city', verbose_name='Город')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.carestate', verbose_name='Состояние')),
                ('truck_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.truckbrand', verbose_name='Марка')),
                ('truck_load_capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.truckloadcapacity', verbose_name='Грузоподъемность')),
                ('truck_transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.trucktransmission', verbose_name='Коробка передач')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.trucktype', verbose_name='Тип грузовика')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший запись')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.year', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Легковой автомобиль',
                'verbose_name_plural': 'Легковые автомобили',
            },
        ),
    ]
