# Generated by Django 4.2.4 on 2023-09-06 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazon_app', '0022_truckbrand_truckloadcapacity_trucktransmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorbikeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марку',
                'verbose_name_plural': 'Мотоциклы - Марки',
            },
        ),
        migrations.CreateModel(
            name='MotorbikeDriveUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Привод')),
            ],
            options={
                'verbose_name': 'Привод',
                'verbose_name_plural': 'Мотоциклы - Типы привода',
            },
        ),
        migrations.CreateModel(
            name='MotorbikeNumberCycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True, verbose_name='Число тактов')),
            ],
            options={
                'verbose_name': 'Число тактов',
                'verbose_name_plural': 'Мотоциклы - Число тактов',
            },
        ),
        migrations.CreateModel(
            name='MotorbikeNumberCylinders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True, verbose_name='Количество цилиндров')),
            ],
            options={
                'verbose_name': 'Количество цилиндров',
                'verbose_name_plural': 'Мотоциклы - Количество цилиндров',
            },
        ),
        migrations.CreateModel(
            name='MotorbikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип мотоцикла')),
            ],
            options={
                'verbose_name': 'Тип мотоцикла',
                'verbose_name_plural': 'Мотоциклы - Типы',
            },
        ),
        migrations.CreateModel(
            name='MotorbikeVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Объём, см³')),
            ],
            options={
                'verbose_name': 'Объём',
                'verbose_name_plural': 'Мотоциклы - Объём',
            },
        ),
        migrations.AlterModelOptions(
            name='bodytype',
            options={'verbose_name': 'Тип кузова', 'verbose_name_plural': 'Легковые авто - Типы кузова'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Легковой автомобиль', 'verbose_name_plural': 'Легковые авто'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Марку', 'verbose_name_plural': 'Легковые авто - Марки'},
        ),
        migrations.AlterModelOptions(
            name='carcolor',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Легковые авто - Цвета'},
        ),
        migrations.AlterModelOptions(
            name='carestate',
            options={'verbose_name': 'Состояние', 'verbose_name_plural': 'Легковые авто - Состояния'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Легковые авто - Модели'},
        ),
        migrations.AlterModelOptions(
            name='driveunit',
            options={'verbose_name': 'Привод', 'verbose_name_plural': 'Легковые авто - Типы привода'},
        ),
        migrations.AlterModelOptions(
            name='enginetype',
            options={'verbose_name': 'Тип двигателя', 'verbose_name_plural': 'Легковые авто - Типы'},
        ),
        migrations.AlterModelOptions(
            name='enginevolume',
            options={'verbose_name': 'Объём двигателя', 'verbose_name_plural': 'Легковые авто - Объёмы двигателей'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'Тип коробки передач', 'verbose_name_plural': 'Легковые авто - Типы коробки передач'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'verbose_name': 'Грузовой автомобиль', 'verbose_name_plural': 'Грузовые авто'},
        ),
        migrations.AlterModelOptions(
            name='truckbrand',
            options={'verbose_name': 'Марку', 'verbose_name_plural': 'Грузовые авто - Марки'},
        ),
        migrations.AlterModelOptions(
            name='truckloadcapacity',
            options={'verbose_name': 'Грузоподъемность', 'verbose_name_plural': 'Грузовые авто - Грузоподъемность'},
        ),
        migrations.AlterModelOptions(
            name='trucktransmission',
            options={'verbose_name': 'Коробку передач', 'verbose_name_plural': 'Грузовые авто - Типы коробки передач'},
        ),
        migrations.AlterModelOptions(
            name='trucktype',
            options={'verbose_name': 'Тип грузовика', 'verbose_name_plural': 'Грузовые авто - Типы'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'Год', 'verbose_name_plural': 'Легковые авто - Годы выпуска'},
        ),
        migrations.CreateModel(
            name='Motorbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название товара/услуги')),
                ('mileage', models.IntegerField(verbose_name='Пробег, км')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('exchange', models.BooleanField(verbose_name='Возможен обмен')),
                ('leasing', models.BooleanField(verbose_name='Лизинг от продавца')),
                ('installment_plan', models.BooleanField(verbose_name='Готов(а) продать товар в рассрочку')),
                ('grade', models.FloatField(default=0, verbose_name='Оценка')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.motorbikebrand', verbose_name='Марка')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.city', verbose_name='Город')),
                ('number_cycles', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.motorbikenumbercycles', verbose_name='Количество тактов')),
                ('number_cylinders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.motorbikenumbercylinders', verbose_name='Количество цилиндров')),
                ('number_volume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.motorbikevolume', verbose_name='Объём, см³')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.carestate', verbose_name='Состояние')),
                ('truck_dive_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.motorbikedriveunit', verbose_name='Привод')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.motorbiketype', verbose_name='Тип мотоцикла')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший запись')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.year', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Легковой автомобиль',
                'verbose_name_plural': 'Мототехника',
            },
        ),
    ]
