# Generated by Django 4.2.4 on 2023-09-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazon_app', '0023_motorbikebrand_motorbikedriveunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCeilingHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Высота потолков')),
            ],
            options={
                'verbose_name': 'Высоту потолков',
                'verbose_name_plural': 'Квартиры - Высоты потолков',
            },
        ),
        migrations.CreateModel(
            name='ApartmentFloors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Этажи',
                'verbose_name_plural': 'Квартиры - Этажи',
            },
        ),
        migrations.CreateModel(
            name='ApartmentLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Вид планировки')),
            ],
            options={
                'verbose_name': 'Вид планировки',
                'verbose_name_plural': 'Квартиры - Виды планировок',
            },
        ),
        migrations.CreateModel(
            name='ApartmentRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Количество комнат',
                'verbose_name_plural': 'Квартиры - Количество комнат',
            },
        ),
        migrations.CreateModel(
            name='ApartmentSalesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Продавца',
                'verbose_name_plural': 'Квартиры - Продавцы',
            },
        ),
        migrations.CreateModel(
            name='ApartmentWallMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Материал стен')),
            ],
            options={
                'verbose_name': 'Материал стен',
                'verbose_name_plural': 'Квартиры - Материалы стен',
            },
        ),
        migrations.AlterModelOptions(
            name='motorbike',
            options={'verbose_name': 'Мотоцикл', 'verbose_name_plural': 'Мотоциклы'},
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название товара/услуги')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('grade', models.FloatField(default=0, verbose_name='Оценка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.category', verbose_name='Категория')),
                ('ceiling_height', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.apartmentceilingheight', verbose_name='Высота потолков')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.city', verbose_name='Город')),
                ('floors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.apartmentfloors', verbose_name='Этажность дома')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.apartmentlayout', verbose_name='Вид планировки')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.apartmentrooms', verbose_name='Количество комнат')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.apartmentsalesman', verbose_name='Продавец')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший запись')),
                ('wall_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.apartmentwallmaterial', verbose_name='Материал стен')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
            },
        ),
    ]
