# Generated by Django 4.2.4 on 2023-09-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0027_dealtype_apartment_deal_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealType',
            new_name='ApartmentDealType',
        ),
    ]
