# Generated by Django 4.2.4 on 2023-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0028_rename_dealtype_apartmentdealtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentceilingheight',
            name='value',
            field=models.CharField(max_length=150, unique=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='apartmentdealtype',
            name='value',
            field=models.CharField(max_length=150, unique=True, verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='apartmentlayout',
            name='value',
            field=models.CharField(max_length=150, unique=True, verbose_name='Вид планировки'),
        ),
        migrations.AlterField(
            model_name='apartmentsalesman',
            name='value',
            field=models.CharField(max_length=150, unique=True, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='apartmentwallmaterial',
            name='value',
            field=models.CharField(max_length=150, unique=True, verbose_name='Материал стен'),
        ),
    ]
