# Generated by Django 4.2.4 on 2023-09-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0031_cottage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cottage',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома, квартиры, дачи'},
        ),
    ]
