# Generated by Django 4.2.4 on 2023-09-06 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazon_app', '0034_audiostate_audiotype_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadphonesConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Тип разъёма')),
            ],
            options={
                'verbose_name': 'Тип разъёма',
                'verbose_name_plural': 'Наушники - Типы разъёмов',
            },
        ),
        migrations.CreateModel(
            name='HeadphonesFastening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Крепление')),
            ],
            options={
                'verbose_name': 'Крепление',
                'verbose_name_plural': 'Наушники - Крепления',
            },
        ),
        migrations.CreateModel(
            name='HeadphonesManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производителя',
                'verbose_name_plural': 'Наушники - Производители',
            },
        ),
        migrations.CreateModel(
            name='HeadphonesPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Наушники - Назначения',
            },
        ),
        migrations.CreateModel(
            name='HeadphonesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Наушники - Типы',
            },
        ),
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Аудиотехнику', 'verbose_name_plural': 'Аудиотехника'},
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название товара/услуги')),
                ('wireless', models.BooleanField(verbose_name='Беспроводные')),
                ('noise_reduction', models.BooleanField(verbose_name='Активное шумоподавление')),
                ('surround_sound', models.BooleanField(verbose_name='Объёмное звучание')),
                ('folding', models.BooleanField(verbose_name='Возможность складывания')),
                ('volume_control', models.BooleanField(verbose_name='Регулировка громкости')),
                ('protection', models.BooleanField(verbose_name='Пыле- и влагозащита')),
                ('microphone', models.BooleanField(verbose_name='Микрофон')),
                ('NFC', models.BooleanField(verbose_name='NFC')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('exchange', models.BooleanField(verbose_name='Возможен обмен')),
                ('installment_plan', models.BooleanField(verbose_name='Готов(а) продать товар в рассрочку')),
                ('grade', models.FloatField(default=0, verbose_name='Оценка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazon_app.subcategory', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.city', verbose_name='Город')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.headphonesconnector', verbose_name='Тип разъёма')),
                ('fastening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.headphonesfastening', verbose_name='Крепление')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.headphonesmanufacturer', verbose_name='Производитель')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.headphonespurpose', verbose_name='Назначение')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.audiostate', verbose_name='Состояние')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.headphonestype', verbose_name='Тип')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший запись')),
            ],
            options={
                'verbose_name': 'Наушники',
                'verbose_name_plural': 'Наушники',
            },
        ),
    ]
