# Generated by Django 4.2.4 on 2023-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0036_videoequipmenttype_videoequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEquipmentManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производителя',
                'verbose_name_plural': 'ТВ и видеотехника - Производители',
            },
        ),
        migrations.DeleteModel(
            name='VideoEquipment',
        ),
    ]
