# Generated by Django 4.2.4 on 2023-09-07 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazon_app', '0038_videoequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OttomansType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Банкетку/пуфик',
                'verbose_name_plural': 'Банкетки и пуфики - Типы',
            },
        ),
        migrations.CreateModel(
            name='OttomansEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название товара/услуги')),
                ('box', models.BooleanField(verbose_name='С ящиком')),
                ('living_room', models.BooleanField(verbose_name='Для гостиной')),
                ('bedroom', models.BooleanField(verbose_name='Для спальни')),
                ('kitchen', models.BooleanField(verbose_name='Для кухни')),
                ('bathroom', models.BooleanField(verbose_name='Для ванной комнаты')),
                ('hallway', models.BooleanField(verbose_name='Для прихожей')),
                ('office', models.BooleanField(verbose_name='Для офиса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('exchange', models.BooleanField(verbose_name='Возможен обмен')),
                ('installment_plan', models.BooleanField(verbose_name='Готов(а) продать товар в рассрочку')),
                ('grade', models.FloatField(default=0, verbose_name='Оценка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazon_app.subcategory', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.city', verbose_name='Город')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.audiostate', verbose_name='Состояние')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazon_app.ottomanstype', verbose_name='Тип')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший запись')),
            ],
            options={
                'verbose_name': 'Банкетку/пуфик',
                'verbose_name_plural': 'Банкетки и пуфики',
            },
        ),
    ]
