# Generated by Django 4.2.4 on 2023-09-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0040_hangerfastening_hangertype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hanger',
        ),
    ]
