# Generated by Django 4.2.4 on 2023-09-07 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazon_app', '0042_hanger_dresser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OttomansEquipment',
            new_name='Ottomans',
        ),
    ]
