# Generated by Django 4.2.4 on 2023-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0043_rename_ottomansequipment_ottomans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('Volkswagen', 'Volkswagen')], max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
    ]
