# Generated by Django 4.2.4 on 2023-09-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0044_cartest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazon_app.brand')),
            ],
        ),
        migrations.AlterField(
            model_name='cartest',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazon_app.brand'),
        ),
        migrations.AlterField(
            model_name='cartest',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazon_app.model'),
        ),
    ]
