# Generated by Django 4.2.4 on 2023-09-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0045_brand_model_alter_cartest_brand_alter_cartest_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartest',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cartest',
            name='model',
        ),
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='CarTest',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
