# Generated by Django 4.2.4 on 2023-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0048_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bodyType',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='carColor',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driveUnit',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engineType',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engineVolume',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Объём двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='state',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='year',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='state',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.CharField(choices=[('00', '00')], max_length=200, verbose_name='Год'),
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
        migrations.DeleteModel(
            name='CarColor',
        ),
        migrations.DeleteModel(
            name='CareState',
        ),
        migrations.DeleteModel(
            name='DriveUnit',
        ),
        migrations.DeleteModel(
            name='EngineType',
        ),
        migrations.DeleteModel(
            name='EngineVolume',
        ),
        migrations.DeleteModel(
            name='Transmission',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
