# Generated by Django 4.2.4 on 2023-09-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazon_app', '0051_alter_apartment_city_alter_audio_city_alter_car_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_load_capacity',
            field=models.CharField(choices=[('< 3 т', '< 3 т'), ('3 т', '3 т'), ('4 т', '4 т'), ('5 т', '5 т'), ('6 т', '6 т'), ('7 т', '7 т'), ('8 т', '8 т'), ('9 т', '9 т'), ('10 т', '10 т'), ('11 т', '11 т'), ('12 т', '12 т'), ('13 т', '13 т'), ('14 т', '14 т'), ('15 т', '15 т'), ('16 т', '16 т'), ('17 т', '17 т'), ('18 т', '18 т'), ('19 т', '19 т'), ('20 т', '20 т'), ('> 20 т', '> 20 т')], max_length=200, verbose_name='Грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_transmission',
            field=models.CharField(choices=[('Автоматическая', 'Автоматическая'), ('Механическая', 'Механическая')], max_length=200, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(choices=[('Полуприцеп', 'Полуприцеп'), ('Рефрижератор', 'Рефрижератор'), ('Контейнеровоз', 'Контейнеровоз'), ('Открытая бортовая', 'Открытая бортовая'), ('Открытая платформа', 'Открытая платформа'), ('Автоцистерна', 'Автоцистерна'), ('Автовоз', 'Автовоз'), ('Зерновоз', 'Зерновоз'), ('Самосвал', 'Самосвал'), ('Лесовоз', 'Лесовоз'), ('Автосцепка', 'Автосцепка'), ('Фургон', 'Фургон'), ('Изотерм', 'Изотерм'), ('Седельный тягач', 'Седельный тягач'), ('Автобус', 'Автобус')], max_length=200, verbose_name='Тип грузовика'),
        ),
        migrations.DeleteModel(
            name='TruckLoadCapacity',
        ),
        migrations.DeleteModel(
            name='TruckTransmission',
        ),
        migrations.DeleteModel(
            name='TruckType',
        ),
    ]
